apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: keycloakclients.k8s.kiwigrid.com
spec:
  group: k8s.kiwigrid.com
  version: v1beta1
  scope: Namespaced
  names:
    kind: KeycloakClient
    singular: keycloakclient
    plural: keycloakclients
    shortNames: [ kcc ]
  additionalPrinterColumns:
  - name: KEYCLOAK
    type: string
    description: The ID for referencing the Keycloak.
    JSONPath: .spec.keycloak
  - name: REALM
    type: string
    description: The realm of the client.
    JSONPath: .spec.realm
  - name: CLIENTID
    type: string
    description: The name of the client.
    JSONPath: .spec.clientId
  - name: TYPE
    type: string
    description: The type of the client.
    JSONPath: .spec.clientType
  - name: TIMESTAMP
    type: string
    description: The timestamp of the realm.
    JSONPath: .status.timestamp
  - name: ERROR
    type: string
    description: The error of the realm.
    JSONPath: .status.error
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - realm
          - clientId
          - clientType
          properties:
            keycloak:
              description: 'Name of Keycloak to use, defaults to: keycloak'
              type: string
            realm:
              description: 'Name of realm to create client in'
              type: string
            clientId:
              description: 'ClientId of client to create'
              type: string
            clientType:
              description: 'Type of client'
              type: string
#             enum:
#             - public
#             - confidential
#             - bearer
            name:
              description: 'Name of client for Keycloak'
              type: string
            enabled:
              description: 'Is client enabled?'
              type: boolean
            directAccessGrantsEnabled:
              type: boolean
            standardFlowEnabled:
              type: boolean
            implicitFlowEnabled:
              type: boolean
            serviceAccountsEnabled:
              type: boolean
            defaultRoles:
              type: array
              items:
                type: string
            defaultClientScopes:
              type: array
              items:
                type: string
            optionalClientScopes:
              type: array
              items:
                type: string
            redirectUris:
              type: array
              items:
                type: string
            webOrigins:
              type: array
              items:
                type: string
            secretNamespace:
              description: 'Namespace of secret for confidential client, default: default'
              type: string
            secretName:
              description: 'Name of secret for confidential client, default: <clientId>'
              type: string
            secretKey:
              description: 'Key in secret for confidential client, default: secret'
              type: string
            mapper:
              description: 'Protocol mappers to use'
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  protocolMapper:
                    type: string
                  config:
                    type: object
                    additionalProperties:
                      type: string
            roles:
              description: 'Client roles with realm composites to create'
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  realmRoles:
                    type: array
                    items: 
                      type: string
        status:
          type: object
          required:
          - timestamp
          properties:
            timestamp:
              type: string
            error:
              type: string